version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pulsecord-postgres
    restart: always
    environment:
      POSTGRES_USER: pulsecord
      POSTGRES_PASSWORD: pulsecordpass
      POSTGRES_DB: pulsecord_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
